general_paths:
  data: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data"
  src: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/src/conda_envs"

paths:
  paralog_sets_dir: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/paralog_sets"
  housekeeping_dir: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/house_keeping_genes"

variables:
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  vertebrata: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"]
  insecta: ["Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi"]
  my_measures: ["sequence_similarities", "expression_similarities"]
  paralog_types: ["BA_comb", "BD_comb", "BA_seq", "BD_seq", "BA_expr", "BD_expr"]
