general_paths:
  data: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data"
  src: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/src/conda_envs"
  nobackup_dir: "/no_backup/mirimia/fmantica/vertebrate_insects_GE"

paths:
  general_patterns: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/general_patterns_v3"
  pca_analysis: "/users/mirimia/fmantica/projects/bilaterian_GE/data/pca_analysis_all_norms"
  gene_sets_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/gene_sets"
  go_transfers: "/users/mirimia/fmantica/projects/bilaterian_GE/data/GO_transfers"
  original_rel_expr_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_call/species_QN_taus/All_version2"
  rel_expr_dir: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/relative_expressions"
  gtf_ref_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/corrected_gtf/All_version2/ref_gene_entries"
  database: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/DB"
  general_patterns_BD: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/general_patterns_BestDivergent"
  general_patterns_BA: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/general_patterns_BestAncestral"
  paralog_sets_dir: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/paralog_sets"

#  metadata: "/users/mirimia/fmantica/projects/bilaterian_GE/data/samples_metadata"
#  database: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB"
#  metasamples_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/metasamples" 
#  average_expr_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/average_expr_by_tissue"
#  gene_sets_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/gene_sets"
#  splsda_analysis: "/users/mirimia/fmantica/projects/bilaterian_GE/data/splsda_analysis"
#  delta_zscore_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/delta_zscores"
#  branches_length_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/branches_length_analysis"  
#  general_patterns: "/users/mirimia/fmantica/projects/bilaterian_GE/data/vertebrates_vs_insects_general_patterns"
#  go_transfers: "/users/mirimia/fmantica/projects/bilaterian_GE/data/GO_transfers"
#  pfam_transfers: "/users/mirimia/fmantica/projects/bilaterian_GE/data/PFAM_transfers"

tools:
  run_gprofiler2: "./bin/run_gprofiler2.R"
  get_gmt_files: "./bin/get_gmt_files.py"
  compute_rel_expr: "./bin/compute_relative_expression.py"
  get_start_stop_info: "./bin/get_start_stop_info.py"
  get_CDS_exons: "./bin/get_CDS_exons.py"
  format_phyloP_scores: "./bin/format_phyloP_scores.R"
  select_best_divergent_orthologs: "./bin/select_best_divergent_orthologs.R"
  select_best_ancestral_orthologs: "./bin/select_best_ancestral_orthologs.R"
  transfer_GO_sets: "./bin/transfer_GO_sets.R"

variables:
  my_version: "All_version2"
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  vertebrata: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"]
  insecta: ["Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi"]
  deuterostoma: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2"]
  protostoma: ["Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  #clades: ["Bilateria"]
  #evo_types: ["conserved"]
  #categories: ["STRICT"]
  #expr_types: ["metasamples_median_expr", "tissue_average_expr"]
  all_tissues: ["Neural", "Muscle", "Testis", "Ovary", "Epithelial", "Kidney", "DigestiveTract", "Adipose"] 
  #higher_GO_cutoff: 2500
  #lower_GO_cutoff: 3
  #expr_suffix: "-NOSVA-log2-TPMs-NORM-BH_genes.tab"
  #reduced_expr_suffix: "NOSVA-log2-TPMs"
  #metasamples_expr_suffix: "-metasamples_median_expr-NOSVA-log2-TPMs-NORM-BH_genes.tab"
  #tissue_expr_suffix: "-tissue_average_expr-NOSVA-log2-TPMs-NORM-BH_genes.tab"
  #paps_clades: ["Bilateria", "Planulozoa", "Eumetazoa", "Metazoa", "Node_2", "Node_1", "Holozoa"]
  #my_measures: ["sequence_similarities", "expression_correlations", "expression_similarities", "expression_distances"]
  #my_measures: ["sequence_similarities", "expression_similarities", "expression_distances", "expression_correlations"]
  my_measures: ["sequence_similarities", "expression_similarities"]
  extra_expr_metrics: ["expression_correlations", "expression_distances"]
  conservation_categories: ["vertebrata_most_conserved", "vertebrata_least_conserved", "insecta_most_conserved", "insecta_least_conserved", "highest_delta", "lowest_delta"]
  paralog_types: ["ALL"]
  #paralog_types: ["BA_comb", "BD_comb", "BA_seq", "BD_seq", "BA_expr", "BD_expr"]
  #go_categories: ["Vertebrata_seqANDexpr_slow_evolving", "Vertebrata_seqNOexpr_slow_evolving", "Insecta_seqANDexpr_slow_evolving", "Insecta_seqNOexpr_slow_evolving", "Vertebrata_seq_slow_evolving", "Vertebrata_expr_slow_evolving", "Insecta_seq_slow_evolving", "Insecta_expr_slow_evolving", "Vertebrata_expr_most_cor", "Vertebrata_expr_least_cor", "Insecta_expr_most_cor", "Insecta_expr_least_cor"]
