general_paths:
  data: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data"
  src: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/src/conda_envs"
  nobackup_dir: "/no_backup/mirimia/fmantica/vertebrate_insects_GE"

paths:
  general_patterns: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/general_patterns"
  gtf_ref_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/corrected_gtf/All_version2/ref_gene_entries"
  database: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/DB"
  paralog_sets_dir: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/paralog_sets"

tools:
  get_gmt_files: "./bin/get_gmt_files.py"
  get_start_stop_info: "./bin/get_start_stop_info.py"
  get_CDS_exons: "./bin/get_CDS_exons.py"
  transfer_GO_sets: "./bin/transfer_GO_sets.R"

variables:
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  vertebrata: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"]
  insecta: ["Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi"]
  my_measures: ["sequence_similarities", "expression_similarities"]
  extra_metrics: ["expression_correlations", "expression_distances", "sequence_similarities_blosum62_maxmin", "sequence_similarities_blosum45_maxmin", "sequence_similarities_original_NoStartEndGaps", "expression_similarities_summed_paralogs"]
  conservation_categories: ["vertebrata_most_conserved", "vertebrata_least_conserved", "insecta_most_conserved", "insecta_least_conserved", "highest_delta", "lowest_delta"]
  paralog_types: ["BA_comb", "BD_comb", "BA_seq", "BD_seq", "BA_expr", "BD_expr"]
