general_paths:
  data: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data"
  src: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/src/conda_envs"
  nobackup_dir: "/no_backup/mirimia/fmantica/vertebrate_insects_GE"

paths:
  rel_expr_dir: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/relative_expressions"
  paralog_sets_dir: "/users/mirimia/fmantica/projects/vertebrate_insect_GE/data/paralog_sets"
  score_matrix_dir: "./downloaded"

tools:
  compute_pairwise_expr_cor: "./bin/compute_pairwise_expr_cor.py"
  compute_pairwise_expr_dist: "./bin/compute_pairwise_expr_dist.py"
  compute_seq_similarity_blosum: "./bin/compute_seq_similarity-blosum.py"
  compute_seq_similarity_original: "./bin/compute_seq_similarity-original.py"
  compute_relative_expr: "./bin/compute_relative_expression.py"
  compute_pairwise_expr_sim_summed_paralogs: "./bin/compute_pairwise_expr_sim-summed_paralogs.py"
  compute_tau: "./bin/compute_tau.py"
  associate_tissue_with_ts: "./bin/associate_tissue_with_ts.py"

variables:
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  vertebrata: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"]
  insecta: ["Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi"]
  all_tissues: ["Neural", "Muscle", "Testis", "Ovary", "Epithelial", "Kidney", "DigestiveTract"]
  orthogroup_file: "/users/mirimia/fmantica/projects/bilaterian_GE/data/gene_sets/All_version2/STRICT/Bilateria/conserved/Bilateria_conserved_orthogroups-EXPR_genes.txt"
